var annotated_dup =
[
    [ "libscratchcpp", "namespacelibscratchcpp.html", [
      [ "test", "namespacelibscratchcpp_1_1test.html", [
        [ "ScriptBuilder", "classlibscratchcpp_1_1test_1_1ScriptBuilder.html", "classlibscratchcpp_1_1test_1_1ScriptBuilder" ]
      ] ],
      [ "Asset", "classlibscratchcpp_1_1Asset.html", "classlibscratchcpp_1_1Asset" ],
      [ "Block", "classlibscratchcpp_1_1Block.html", "classlibscratchcpp_1_1Block" ],
      [ "BlockPrototype", "classlibscratchcpp_1_1BlockPrototype.html", "classlibscratchcpp_1_1BlockPrototype" ],
      [ "Broadcast", "classlibscratchcpp_1_1Broadcast.html", "classlibscratchcpp_1_1Broadcast" ],
      [ "Comment", "classlibscratchcpp_1_1Comment.html", "classlibscratchcpp_1_1Comment" ],
      [ "Compiler", "classlibscratchcpp_1_1Compiler.html", "classlibscratchcpp_1_1Compiler" ],
      [ "CompilerConstant", "classlibscratchcpp_1_1CompilerConstant.html", "classlibscratchcpp_1_1CompilerConstant" ],
      [ "CompilerContext", "classlibscratchcpp_1_1CompilerContext.html", "classlibscratchcpp_1_1CompilerContext" ],
      [ "CompilerLocalVariable", "classlibscratchcpp_1_1CompilerLocalVariable.html", "classlibscratchcpp_1_1CompilerLocalVariable" ],
      [ "CompilerValue", "classlibscratchcpp_1_1CompilerValue.html", "classlibscratchcpp_1_1CompilerValue" ],
      [ "Costume", "classlibscratchcpp_1_1Costume.html", "classlibscratchcpp_1_1Costume" ],
      [ "Drawable", "classlibscratchcpp_1_1Drawable.html", "classlibscratchcpp_1_1Drawable" ],
      [ "Entity", "classlibscratchcpp_1_1Entity.html", "classlibscratchcpp_1_1Entity" ],
      [ "ExecutableCode", "classlibscratchcpp_1_1ExecutableCode.html", "classlibscratchcpp_1_1ExecutableCode" ],
      [ "ExecutionContext", "classlibscratchcpp_1_1ExecutionContext.html", "classlibscratchcpp_1_1ExecutionContext" ],
      [ "Field", "classlibscratchcpp_1_1Field.html", "classlibscratchcpp_1_1Field" ],
      [ "IEngine", "classlibscratchcpp_1_1IEngine.html", "classlibscratchcpp_1_1IEngine" ],
      [ "IExtension", "classlibscratchcpp_1_1IExtension.html", "classlibscratchcpp_1_1IExtension" ],
      [ "IGraphicsEffect", "classlibscratchcpp_1_1IGraphicsEffect.html", "classlibscratchcpp_1_1IGraphicsEffect" ],
      [ "IMonitorHandler", "classlibscratchcpp_1_1IMonitorHandler.html", "classlibscratchcpp_1_1IMonitorHandler" ],
      [ "Input", "classlibscratchcpp_1_1Input.html", "classlibscratchcpp_1_1Input" ],
      [ "InputValue", "classlibscratchcpp_1_1InputValue.html", "classlibscratchcpp_1_1InputValue" ],
      [ "IRandomGenerator", "classlibscratchcpp_1_1IRandomGenerator.html", "classlibscratchcpp_1_1IRandomGenerator" ],
      [ "ISpriteHandler", "classlibscratchcpp_1_1ISpriteHandler.html", "classlibscratchcpp_1_1ISpriteHandler" ],
      [ "IStackTimer", "classlibscratchcpp_1_1IStackTimer.html", "classlibscratchcpp_1_1IStackTimer" ],
      [ "IStageHandler", "classlibscratchcpp_1_1IStageHandler.html", "classlibscratchcpp_1_1IStageHandler" ],
      [ "ITimer", "classlibscratchcpp_1_1ITimer.html", "classlibscratchcpp_1_1ITimer" ],
      [ "KeyEvent", "classlibscratchcpp_1_1KeyEvent.html", "classlibscratchcpp_1_1KeyEvent" ],
      [ "List", "classlibscratchcpp_1_1List.html", "classlibscratchcpp_1_1List" ],
      [ "Monitor", "classlibscratchcpp_1_1Monitor.html", "classlibscratchcpp_1_1Monitor" ],
      [ "Project", "classlibscratchcpp_1_1Project.html", "classlibscratchcpp_1_1Project" ],
      [ "Promise", "classlibscratchcpp_1_1Promise.html", "classlibscratchcpp_1_1Promise" ],
      [ "Rect", "classlibscratchcpp_1_1Rect.html", "classlibscratchcpp_1_1Rect" ],
      [ "ScratchConfiguration", "classlibscratchcpp_1_1ScratchConfiguration.html", "classlibscratchcpp_1_1ScratchConfiguration" ],
      [ "Script", "classlibscratchcpp_1_1Script.html", "classlibscratchcpp_1_1Script" ],
      [ "Sound", "classlibscratchcpp_1_1Sound.html", "classlibscratchcpp_1_1Sound" ],
      [ "Sprite", "classlibscratchcpp_1_1Sprite.html", "classlibscratchcpp_1_1Sprite" ],
      [ "Stage", "classlibscratchcpp_1_1Stage.html", "classlibscratchcpp_1_1Stage" ],
      [ "StringPtr", "structlibscratchcpp_1_1StringPtr.html", "structlibscratchcpp_1_1StringPtr" ],
      [ "Target", "classlibscratchcpp_1_1Target.html", "classlibscratchcpp_1_1Target" ],
      [ "TextBubble", "classlibscratchcpp_1_1TextBubble.html", "classlibscratchcpp_1_1TextBubble" ],
      [ "Thread", "classlibscratchcpp_1_1Thread.html", "classlibscratchcpp_1_1Thread" ],
      [ "Value", "classlibscratchcpp_1_1Value.html", "classlibscratchcpp_1_1Value" ],
      [ "ValueData", "structlibscratchcpp_1_1ValueData.html", "structlibscratchcpp_1_1ValueData" ],
      [ "Variable", "classlibscratchcpp_1_1Variable.html", "classlibscratchcpp_1_1Variable" ]
    ] ]
];