var annotated_dup =
[
    [ "libscratchcpp", "namespacelibscratchcpp.html", [
      [ "sigslot", "namespacelibscratchcpp_1_1sigslot.html", [
        [ "detail", "namespacelibscratchcpp_1_1sigslot_1_1detail.html", [
          [ "mock", "namespacelibscratchcpp_1_1sigslot_1_1detail_1_1mock.html", [
            [ "a", "structlibscratchcpp_1_1sigslot_1_1detail_1_1mock_1_1a.html", "structlibscratchcpp_1_1sigslot_1_1detail_1_1mock_1_1a" ],
            [ "b", "structlibscratchcpp_1_1sigslot_1_1detail_1_1mock_1_1b.html", "structlibscratchcpp_1_1sigslot_1_1detail_1_1mock_1_1b" ],
            [ "c", "structlibscratchcpp_1_1sigslot_1_1detail_1_1mock_1_1c.html", "structlibscratchcpp_1_1sigslot_1_1detail_1_1mock_1_1c" ],
            [ "d", "structlibscratchcpp_1_1sigslot_1_1detail_1_1mock_1_1d.html", "structlibscratchcpp_1_1sigslot_1_1detail_1_1mock_1_1d" ],
            [ "fun_types", "unionlibscratchcpp_1_1sigslot_1_1detail_1_1mock_1_1fun__types.html", "unionlibscratchcpp_1_1sigslot_1_1detail_1_1mock_1_1fun__types" ]
          ] ],
          [ "cleanable", "structlibscratchcpp_1_1sigslot_1_1detail_1_1cleanable.html", "structlibscratchcpp_1_1sigslot_1_1detail_1_1cleanable" ],
          [ "copy_on_write", "classlibscratchcpp_1_1sigslot_1_1detail_1_1copy__on__write.html", "classlibscratchcpp_1_1sigslot_1_1detail_1_1copy__on__write" ],
          [ "func_ptr", "structlibscratchcpp_1_1sigslot_1_1detail_1_1func__ptr.html", "structlibscratchcpp_1_1sigslot_1_1detail_1_1func__ptr" ],
          [ "function_traits", "structlibscratchcpp_1_1sigslot_1_1detail_1_1function__traits.html", null ],
          [ "function_traits< T *, std::enable_if_t< trait::is_func_v< T > > >", "structlibscratchcpp_1_1sigslot_1_1detail_1_1function__traits_3_01T_01_5_00_01std_1_1enable__if__fab79e8f6bae505a3ed1e044cb96913f.html", null ],
          [ "function_traits< T, std::enable_if_t< trait::has_call_operator_v< T > > >", "structlibscratchcpp_1_1sigslot_1_1detail_1_1function__traits_3_01T_00_01std_1_1enable__if__t_3_09557ba5f4f46e890ae00247ef4c5c2de.html", "structlibscratchcpp_1_1sigslot_1_1detail_1_1function__traits_3_01T_00_01std_1_1enable__if__t_3_09557ba5f4f46e890ae00247ef4c5c2de" ],
          [ "function_traits< T, std::enable_if_t< trait::is_func_v< T > > >", "structlibscratchcpp_1_1sigslot_1_1detail_1_1function__traits_3_01T_00_01std_1_1enable__if__t_3_03842a49844f7fe0b0773264dfbb9215a.html", null ],
          [ "function_traits< T, std::enable_if_t< trait::is_pmf_v< T > > >", "structlibscratchcpp_1_1sigslot_1_1detail_1_1function__traits_3_01T_00_01std_1_1enable__if__t_3_043712f7274ca0bc5adc1ebfa77340932.html", null ],
          [ "null_mutex", "structlibscratchcpp_1_1sigslot_1_1detail_1_1null__mutex.html", "structlibscratchcpp_1_1sigslot_1_1detail_1_1null__mutex" ],
          [ "object_pointer", "structlibscratchcpp_1_1sigslot_1_1detail_1_1object__pointer.html", null ],
          [ "object_pointer< T *, std::enable_if_t< trait::is_pointer_v< T * > > >", "structlibscratchcpp_1_1sigslot_1_1detail_1_1object__pointer_3_01T_01_5_00_01std_1_1enable__if__tbed174b4c73e6dfa1c80195cb76fccfc.html", null ],
          [ "object_pointer< T, std::enable_if_t< trait::is_weak_ptr_v< T > > >", "structlibscratchcpp_1_1sigslot_1_1detail_1_1object__pointer_3_01T_00_01std_1_1enable__if__t_3_01208f447a1bd6172eae36ce54effdc451.html", null ],
          [ "object_pointer< T, std::enable_if_t<!trait::is_pointer_v< T > &&!trait::is_weak_ptr_v< T > &&trait::is_weak_ptr_compatible_v< T > > >", "structlibscratchcpp_1_1sigslot_1_1detail_1_1object__pointer_3_01T_00_01std_1_1enable__if__t_3_9t107f08fe6489126339c0cda29cee32ff.html", null ],
          [ "observer_type", "structlibscratchcpp_1_1sigslot_1_1detail_1_1observer__type.html", null ],
          [ "signal_wrapper", "structlibscratchcpp_1_1sigslot_1_1detail_1_1signal__wrapper.html", "structlibscratchcpp_1_1sigslot_1_1detail_1_1signal__wrapper" ],
          [ "slot", "classlibscratchcpp_1_1sigslot_1_1detail_1_1slot.html", "classlibscratchcpp_1_1sigslot_1_1detail_1_1slot" ],
          [ "slot_base", "classlibscratchcpp_1_1sigslot_1_1detail_1_1slot__base.html", "classlibscratchcpp_1_1sigslot_1_1detail_1_1slot__base" ],
          [ "slot_extended", "classlibscratchcpp_1_1sigslot_1_1detail_1_1slot__extended.html", "classlibscratchcpp_1_1sigslot_1_1detail_1_1slot__extended" ],
          [ "slot_pmf", "classlibscratchcpp_1_1sigslot_1_1detail_1_1slot__pmf.html", "classlibscratchcpp_1_1sigslot_1_1detail_1_1slot__pmf" ],
          [ "slot_pmf_extended", "classlibscratchcpp_1_1sigslot_1_1detail_1_1slot__pmf__extended.html", "classlibscratchcpp_1_1sigslot_1_1detail_1_1slot__pmf__extended" ],
          [ "slot_pmf_tracked", "classlibscratchcpp_1_1sigslot_1_1detail_1_1slot__pmf__tracked.html", "classlibscratchcpp_1_1sigslot_1_1detail_1_1slot__pmf__tracked" ],
          [ "slot_state", "classlibscratchcpp_1_1sigslot_1_1detail_1_1slot__state.html", "classlibscratchcpp_1_1sigslot_1_1detail_1_1slot__state" ],
          [ "slot_tracked", "classlibscratchcpp_1_1sigslot_1_1detail_1_1slot__tracked.html", "classlibscratchcpp_1_1sigslot_1_1detail_1_1slot__tracked" ],
          [ "spin_mutex", "structlibscratchcpp_1_1sigslot_1_1detail_1_1spin__mutex.html", "structlibscratchcpp_1_1sigslot_1_1detail_1_1spin__mutex" ]
        ] ],
        [ "trait", "namespacelibscratchcpp_1_1sigslot_1_1trait.html", [
          [ "detail", "namespacelibscratchcpp_1_1sigslot_1_1trait_1_1detail.html", [
            [ "has_call_operator", "structlibscratchcpp_1_1sigslot_1_1trait_1_1detail_1_1has__call__operator.html", null ],
            [ "has_call_operator< F, void_t< decltype(&std::remove_reference< F >::type::operator())> >", "structlibscratchcpp_1_1sigslot_1_1trait_1_1detail_1_1has__call__operator_3_01F_00_01void__t_3_0120786f611e687cc56455f33856dd4adc.html", null ],
            [ "is_callable", "structlibscratchcpp_1_1sigslot_1_1trait_1_1detail_1_1is__callable.html", null ],
            [ "is_callable< F, P, typelist< T... >, void_t< decltype(((*std::declval< P >()).*std::declval< F >())(std::declval< T >()...))> >", "structlibscratchcpp_1_1sigslot_1_1trait_1_1detail_1_1is__callable_3_01F_00_01P_00_01typelist_3_017c8a914e0739014729bfd57d960917a.html", null ],
            [ "is_callable< F, typelist< T... >, void_t< decltype(std::declval< F >()(std::declval< T >()...))> >", "structlibscratchcpp_1_1sigslot_1_1trait_1_1detail_1_1is__callable_3_01F_00_01typelist_3_01T_8_8_e70cc0173dce1a00fa41302f87536cd5.html", null ],
            [ "is_signal", "structlibscratchcpp_1_1sigslot_1_1trait_1_1detail_1_1is__signal.html", null ],
            [ "is_signal< signal_base< L, T... > >", "structlibscratchcpp_1_1sigslot_1_1trait_1_1detail_1_1is__signal_3_01signal__base_3_01L_00_01T_8_8_8_01_4_01_4.html", null ],
            [ "is_weak_ptr", "structlibscratchcpp_1_1sigslot_1_1trait_1_1detail_1_1is__weak__ptr.html", null ],
            [ "is_weak_ptr< T, void_t< decltype(std::declval< T >().expired()), decltype(std::declval< T >().lock()), decltype(std::declval< T >().reset())> >", "structlibscratchcpp_1_1sigslot_1_1trait_1_1detail_1_1is__weak__ptr_3_01T_00_01void__t_3_01declty3f049787b9b53fee9d937b1f6d0ded71.html", null ],
            [ "is_weak_ptr_compatible", "structlibscratchcpp_1_1sigslot_1_1trait_1_1detail_1_1is__weak__ptr__compatible.html", null ],
            [ "is_weak_ptr_compatible< T, void_t< decltype(to_weak(std::declval< T >()))> >", "structlibscratchcpp_1_1sigslot_1_1trait_1_1detail_1_1is__weak__ptr__compatible_3_01T_00_01void__123a3d42d73f401d0fe7a72a916f3e0d.html", null ],
            [ "voider", "structlibscratchcpp_1_1sigslot_1_1trait_1_1detail_1_1voider.html", "structlibscratchcpp_1_1sigslot_1_1trait_1_1detail_1_1voider" ]
          ] ],
          [ "typelist", "structlibscratchcpp_1_1sigslot_1_1trait_1_1typelist.html", null ]
        ] ],
        [ "connection", "classlibscratchcpp_1_1sigslot_1_1connection.html", "classlibscratchcpp_1_1sigslot_1_1connection" ],
        [ "connection_blocker", "classlibscratchcpp_1_1sigslot_1_1connection__blocker.html", "classlibscratchcpp_1_1sigslot_1_1connection__blocker" ],
        [ "observer_base", "structlibscratchcpp_1_1sigslot_1_1observer__base.html", "structlibscratchcpp_1_1sigslot_1_1observer__base" ],
        [ "scoped_connection", "classlibscratchcpp_1_1sigslot_1_1scoped__connection.html", "classlibscratchcpp_1_1sigslot_1_1scoped__connection" ],
        [ "signal_base", "classlibscratchcpp_1_1sigslot_1_1signal__base.html", "classlibscratchcpp_1_1sigslot_1_1signal__base" ]
      ] ],
      [ "Asset", "classlibscratchcpp_1_1Asset.html", "classlibscratchcpp_1_1Asset" ],
      [ "Block", "classlibscratchcpp_1_1Block.html", "classlibscratchcpp_1_1Block" ],
      [ "BlockPrototype", "classlibscratchcpp_1_1BlockPrototype.html", "classlibscratchcpp_1_1BlockPrototype" ],
      [ "Broadcast", "classlibscratchcpp_1_1Broadcast.html", "classlibscratchcpp_1_1Broadcast" ],
      [ "Comment", "classlibscratchcpp_1_1Comment.html", "classlibscratchcpp_1_1Comment" ],
      [ "Compiler", "classlibscratchcpp_1_1Compiler.html", "classlibscratchcpp_1_1Compiler" ],
      [ "Costume", "classlibscratchcpp_1_1Costume.html", "classlibscratchcpp_1_1Costume" ],
      [ "Entity", "classlibscratchcpp_1_1Entity.html", "classlibscratchcpp_1_1Entity" ],
      [ "Field", "classlibscratchcpp_1_1Field.html", "classlibscratchcpp_1_1Field" ],
      [ "IBlockSection", "classlibscratchcpp_1_1IBlockSection.html", "classlibscratchcpp_1_1IBlockSection" ],
      [ "IEngine", "classlibscratchcpp_1_1IEngine.html", "classlibscratchcpp_1_1IEngine" ],
      [ "IExtension", "classlibscratchcpp_1_1IExtension.html", "classlibscratchcpp_1_1IExtension" ],
      [ "IGraphicsEffect", "classlibscratchcpp_1_1IGraphicsEffect.html", "classlibscratchcpp_1_1IGraphicsEffect" ],
      [ "IMonitorHandler", "classlibscratchcpp_1_1IMonitorHandler.html", "classlibscratchcpp_1_1IMonitorHandler" ],
      [ "Input", "classlibscratchcpp_1_1Input.html", "classlibscratchcpp_1_1Input" ],
      [ "InputValue", "classlibscratchcpp_1_1InputValue.html", "classlibscratchcpp_1_1InputValue" ],
      [ "ISpriteHandler", "classlibscratchcpp_1_1ISpriteHandler.html", "classlibscratchcpp_1_1ISpriteHandler" ],
      [ "IStageHandler", "classlibscratchcpp_1_1IStageHandler.html", "classlibscratchcpp_1_1IStageHandler" ],
      [ "ITimer", "classlibscratchcpp_1_1ITimer.html", "classlibscratchcpp_1_1ITimer" ],
      [ "KeyEvent", "classlibscratchcpp_1_1KeyEvent.html", "classlibscratchcpp_1_1KeyEvent" ],
      [ "List", "classlibscratchcpp_1_1List.html", "classlibscratchcpp_1_1List" ],
      [ "Monitor", "classlibscratchcpp_1_1Monitor.html", "classlibscratchcpp_1_1Monitor" ],
      [ "Project", "classlibscratchcpp_1_1Project.html", "classlibscratchcpp_1_1Project" ],
      [ "Rect", "classlibscratchcpp_1_1Rect.html", "classlibscratchcpp_1_1Rect" ],
      [ "ScratchConfiguration", "classlibscratchcpp_1_1ScratchConfiguration.html", "classlibscratchcpp_1_1ScratchConfiguration" ],
      [ "Script", "classlibscratchcpp_1_1Script.html", "classlibscratchcpp_1_1Script" ],
      [ "Sound", "classlibscratchcpp_1_1Sound.html", "classlibscratchcpp_1_1Sound" ],
      [ "Sprite", "classlibscratchcpp_1_1Sprite.html", "classlibscratchcpp_1_1Sprite" ],
      [ "Stage", "classlibscratchcpp_1_1Stage.html", "classlibscratchcpp_1_1Stage" ],
      [ "Target", "classlibscratchcpp_1_1Target.html", "classlibscratchcpp_1_1Target" ],
      [ "Value", "classlibscratchcpp_1_1Value.html", "classlibscratchcpp_1_1Value" ],
      [ "Variable", "classlibscratchcpp_1_1Variable.html", "classlibscratchcpp_1_1Variable" ],
      [ "VirtualMachine", "classlibscratchcpp_1_1VirtualMachine.html", "classlibscratchcpp_1_1VirtualMachine" ]
    ] ]
];